### ISSUE TITLE
str2webpstr

### ISSUE THREAD

**Issue by PedroBatistop** [Givemeurcookies/webp-converter#1]
```
Error: ENOENT: no such file or directory, open 'C:\Users\p-edr\Documents\bot\iris-megumim\node_modules\promised-webp-converter\temp\ff3ac8bc-80fd-4f79-9b84-7fb7fa6aecb2.gif'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at base64_to_image (C:\Users\p-edr\Documents\bot\iris-megumim\node_modules\promised-webp-converter\src\buffer_utils.js:30:8)
    at Object.module.exports.base64str2webp (C:\Users\p-edr\Documents\bot\iris-megumim\node_modules\promised-webp-converter\src\buffer_utils.js:53:18)
    at Object.module.exports.str2webpstr (C:\Users\p-edr\Documents\bot\iris-megumim\node_modules\promised-webp-converter\src\webpconverter.js:25:23)
```

**Comment by ohabash** [comment]
You might have to mkdir that path. however Google Cloud Functions wont allow it. so im wondering if this cant be used with gcf

```
async function mkdir(path: string = './node_modules/webp-converter/temp') {
  try {
    await fs.promises.access(path);
    console.log(`Directory ${path} already exists.`);
  } catch (err) {
    await fs.promises.mkdir(path);
    console.log(`Directory ${path} created successfully!`);
  }
  return true;
}
```
